---
title: "Timeline on fields of covariances"
date: "2025-05-18"
tags:
  - idee
  - memento
  - accademia/NCP
  - accademia/fields-of-covariances
  - accademia/statistical-categories
---

# 2025-05-27 states and fields of Hilbert spaces

Discussing with Gemini 2.5 pro (see my zotero), I realized the idea of a "GNS bundle" over the space of states $\mathcal{S}(\mathscr{A})$ on $\mathscr{A}$ must be replaced with the idea of a field of Hilbert spaces because of varying dimensions. 

# 2025-05-23 estimators as sections of the GNS bundle

While driving back home, I realized that statistical estimators are section of the "GNS bundle" over the space of states $\mathcal{S}(\mathscr{A})$ on $\mathscr{A}$. Then, when $i:M\rightarrow \mathcal{S}(\mathscr{A})$, I can pull-back the estimator to the model. 

# 2025-03-01 fields of covariances and metric tensor as functors

This note has been written on 2025-05-18, and the date 2025-03-01 is the best approximation of the original date I came up with. 

---

Recently, together with Laura, we developed the idea that an interesting way of looking at Riemannian metric tensors is as functors from $\mathsf{C}(M)$ (a manifold seen as a category) to $\mathsf{Hilb}_{\mathbb{R}}$. If a Lie group acts on $M$, invariant Riemannian metric tensors are functor from the action groupoid to $\mathsf{Hilb}_{\mathbb{R}}$. Contravariant Riemannian metric tensors are contravariant functors.

This point of view is particularly useful for $\mathsf{NCP}$ because it makes fields of covariances become functors from $\mathsf{NCP}$ to $\mathsf{Hilb}$, thus making them elegant. Moreover, the GNS construction is clearly a functor from $\mathsf{NCP}$ to $\mathsf{Hilb}$ (a fact so trivial yet nowhere to be found in the literature).



# 2023-10-26 fields of covariances on non-faithful states

Referring to the "Čencov meets Petz" problem, perhaps, the way to address the non-faithful states is by suitably choosing the notion of continuity of the covariance field. Roughly speaking, since $\mathcal{H}_{qp}$ is the kernel of $\Delta_{\rho}$, a suitable continuity condition can allow us to say that, given a net $\rho_{\lambda}$ of faithful states that converges to $\rho$, the covariance operator $T_{\rho}$ on $\mathcal{H}_{qp}$ is the limit of $T_{\rho_{\lambda}}=F(\Delta_{\rho_{\lambda}})$ which will then be determined by $F(0)$. I have no clue of which topology one should use, nor of which concrete object should be continuous. However, I believe in this idea. 

# 2023-10-23 the tracial states on type I factors determine the fields of covariances on rational tracial states

After the seminar "Čencov meets Petz" for the Groupoid's Group, I spoke with Fabio DC, and we realized that the way to get the covariance on any rational trace on a finite-dimensional algebra $\mathscr{A}\cong\bigoplus_{j=1}^{N}\mathcal{B}(\mathcal{H}_{j})$ is to immerse such an algebra into $\mathcal{B}(\mathcal{H})$ with $\mathcal{H}=\bigoplus_{k=1}^{NL}\mathcal{K}_{k}$ with $\mathcal{K}_{k}\cong\bigotimes_{j=1}^{N}\mathcal{H}_{j}$. When $L=1$, $\mathcal{B}(\mathcal{H}_{1})$ is sent into $\mathcal{B}(\mathcal{K}_{1})$ setting the others to the identity, and proceeding in analogy. When $L>1$, I choose which $\mathcal{B}(\mathcal{H}_{j})$ gets represented multiple times.  

# 2023-10-17 is normality necessary in NCP?

While giving the seminar on "Čencov meets Petz" for the Groupoid's Group, I realized that maybe the normality condition in $\mathsf{NCP}$ is not really necessary. At the level of the GNS Hilbert space, even if $\rho$ is not faithful, we can characterize what would be $\mathcal{H}_{\rho}^{qp}$ as the kernel of the Tomita operator $S_{\rho}$. If everything works, dropping normality may be useful because we recover a lot of conditional expectations into $\mathcal{B}(\mathcal{H})$ with $\mathcal{H}$ separable. 

# 2023-10-06 covariance at a faithful state is determined by the covariance on the GNS Hilbert space

I believe the covariance at a normal, faithful state $\rho$ with separable GNS space $\mathcal{H}_{\rho}$  is determined by the covariance at the normal, faithful state $\tilde{\rho}$ on $\mathcal{B}(\mathcal{H}_{\rho})$ extending $\rho$. The idea is to show that the representation of $\mathcal{A}$ in $\mathcal{B}(\mathcal{H}_{\rho}$) gives a subalgebra which is invariant w.r.t. the modular flow of $\tilde{\rho}$ and then use invariance w.r.t. congruent embeddings/conditional expectations.  

On 2023-11-04, I wrote somewhere that, together with Fabio DC, we realized this idea is wrong, but I did not write why. It would be nice to know.

# 2023-09-25 GNS-bundle and pullback of fields of covariances

 Motivated by the chat with Laura Elena González Bravo, I thought that a good way to start reasoning about how to "pull back" covariance fields from NCP to a statistical groupoid is that of building a kind of pull-back bundle whose fiber is generated by the GNS Hilbert space. I believe taking the base of the statistical groupoid as the base of this fiber bundle is the easier thing to do, but then I have no idea about the role played by morphisms. Perhaps, the bundle gives the "metric" and the morphisms give symmetries? Would it be possible to build a bundle with the GNS and the morphism space? 
 
# 2023-09-21 centralizers, countably-decomposable algebras, and infinite-dimensional Čencov-Petz

 Mentre guidavo mi sono reso conto che il centralizzatore $\mathscr{M}_{\rho}$ di uno stato normale $\rho$ su una W*-algebra $\mathscr{A}$ deve necessariamente essere un'algebra "countably-decomposable" perché lo stato $\rho$ è fedele su $\mathscr{M}_{\rho}$. Inoltre, $\rho$ è una traccia su $\mathscr{M}_{\rho}$, e quindi il centralizzatore è sempre un'algebra molto particolare. La congettura che abbiamo formulato con Fabio DC è che i centralizzatori con le loro tracce sono le controparti "corrette" dei sistemi classici di Cencov. Cosa comporta il fatto che tutte queste algebre sono "countably decomposable"? Tenendo in conto che per queste algebre esistono "conditional expectations" normali in $\mathcal{B}(\mathcal{H})$, e tenendo in conto il teorema di Takesaki sulle "conditional expectations", forse c'è speranza di fare qualcosa anche a dimensione infinita. 

# 2023-09-12 gli stati tracciali mantengono l'unicità a la Čencov

  Anche oggi ho fatto un po' di ricerca! Tralasciando una mezz'ora passata a cercare di cavare un ragno dal buco delle superalgebre di Jordan, insieme a Fabio DC abbiamo pensato una cosa interessante: la parte classica della categoria NCP non è data dalle algebre commutative, ma dagli stati tracciali. È per gli stati tracciali che il teorema di Čencov **deve** essere vero. Speriamo di riuscire a finire questo lavoro. 