project:
  type: website
  output-dir: docs   # GitHub Pages looks here
  render:
    - "**/*.qmd"
    - "!**/_drafts/**"
    - "!**/*-draft.qmd"
    - "!**/*-draft.ipynb"
website:
  title: "Florio M. Ciaglia"
  description: "You thought he was a man, but he only was a muffin."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Conferences & Seminars
        href: conferences.qmd  
      - text: Miscellanea
        href: index_misc.qmd
#      - text: Publications
#        href: publications/
#      - text: Teaching
#        href: teaching/teaching_index.qmd      
    right:
      - icon: github
        href: https://github.com/f-mc2/fmc
  sidebar:
    style: "docked"
    contents:
      - section: "Courses"
        href: courses/courses_index.qmd
        contents:
          # auto-pick each course landing page
          - auto: courses/*/*.qmd
            sort: title
      - section: "Publications"
        href: publications/publications_index.qmd
        contents:
          - publications/inf-geo.qmd
          - publications/grpd.qmd
          - publications/misc.qmd
          - publications/preprints.qmd
          - publications/articles.qmd
          - publications/proceedings.qmd
      - section: "Presentations"
        href: presentations/presentations_index.qmd
        contents:    
          - auto: presentations/*/*.qmd
            sort: title
#      - section: "Miscellanea"
#        href: index_misc.qmd
#        contents:
#        - auto: misc/*.{qmd,ipynb,md}
#          sort: "date desc"
  comments:
    giscus:
      repo: f-mc2/personal-page-giscus
      repo-id: R_kgDOQHY3cg
      category: General
      category-id: DIC_kwDOQHY3cs4Cw8t9
      mapping: pathname
      reactions-enabled: true
      input-position: bottom
      theme:
        light: light
        dark: dark_dimmed

serve:
  port: 4329
  browser: true

format:
  html:
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://tikzjax.com/v1/fonts.css">
    include-after-body: 
      - includes/tikz-preamble.html
      - includes/after-body.html
    theme: 
      light: cosmo    
      dark: darkly    
    toggle: true      # adds the switch in the navbar
    css: css/style.css
    toc: true
    code-fold: true
    code-summary: "Show/Hide code"

execute:
  echo: true
  warning: false
  error: false
  freeze: auto      # only rerun cells if source changes
  executable: .venv/bin/python   # force Quarto to use your venv


