---
title: "Conferences & Seminars"
format: html
comments: false
---



## Organization of conferences and workshops:
<ol reversed>
<li><strong>When quantum field theory meets quantum information</strong> -- Madrid, Spain, December 2025. Local Organizer.</li>

<li><strong>Geometric Science of Information GSI'25</strong> -- Palais du Grand Large, Saint Malo, France, October 2025. Scientific Committee, Co-chairman of the session "Geometry of Classical and Quantum States". [<a href="https://conference-gsi.org/gsi-2025/about/committees/">committees</a>] [<a href="https://web.archive.org/web/20250603160804/https://conference-gsi.org/gsi-2025/about/committees/">committees-archive</a>] [<a href="https://conference-gsi.org/gsi-2025/program/30-october-2025/">program</a>] [<a href="https://web.archive.org/web/20251204085858/https://conference-gsi.org/gsi-2025/program/30-october-2025/">program-archive</a>]</li>

<li><strong>IX International Workshop on Information Geometry, Quantum Mechanics and Applications 2025</strong> -- UC3M, Madrid, Spain, March 2025. Local Organizer. [<a href="http://www.q-math.es/conferences/IGQMA2025/">conference</a>]</li>

<li><strong>The XXXIX RSEF Physics Biennial</strong> -- Donostia/San Sebastián, Spain, July 2024. Symposia Organizer. [<a href="https://bienalfisica.org/en/symposia#headingSimposio15">conference</a>] [<a href="https://web.archive.org/web/20241006210554/https://bienalfisica.org/en/symposia#headingSimposio15">conference-archive</a>]</li>

<li><strong>VI International Workshop on Information Geometry, Quantum Mechanics and Applications 2024</strong> -- UC3M, Madrid, Spain, March 2024. Local Organizer. [<a href="http://www.q-math.es/conferences/IGQMA2024/">conference</a>] [<a href="https://web.archive.org/web/20240302140129/http://www.q-math.es/conferences/IGQMA2024/">conference-archive</a>]</li>

<li><strong>Geometry of Information Theory</strong> -- UC3M, Madrid, Spain, 2023. Local Organizer. [<a href="https://events.unibo.it/infogeo2023">conference</a>] [<a href="https://web.archive.org/web/20240302134446/https://events.unibo.it/infogeo2023">conference-archive</a>]</li>

<li><strong>Geometric Science of Information GSI'23</strong> -- Palais du Grand Large, Saint Malo, France, September 2023. Scientific Committee, Co-chairman of the session "Geometry of Quantum States". [<a href="https://conference-gsi.org/program/">program</a>] [<a href="https://web.archive.org/web/20240302134625/https://conference-gsi.org/program/">program-archive</a>]</li>

<li><strong>V International Workshop on Information Geometry, Quantum Mechanics and Applications 2023</strong> -- UC3M, Madrid, Spain, March 2023. Local Organizer. [<a href="http://www.q-math.es/conferences/IGQMA2023/">conference</a>] [<a href="https://web.archive.org/web/20240302135319/http://www.q-math.es/conferences/IGQMA2023/">conference-archive</a>]</li>

<li><strong>Geometric Science of Information GSI'21</strong> -- Sorbonne University, Paris, France, August 2021. Scientific Committee, Co-chairman of the session "Geometry of Quantum States". [<a href="https://web2.see.asso.fr/en/wiki/367178_committees">committees</a>] [<a href="https://web2.see.asso.fr/en/wiki/369007_program-schedule">program</a>]</li>

<li><strong>Geometric Science of Information GSI'19</strong> -- ENAC, Toulouse, France, August 2019. Co-chairman of the session "Geometry of Quantum States". [<a href="https://web2.see.asso.fr/en/fichier/26060_schedule-and-final-program">program</a>]</li>

<li><strong>II International Workshop on Information Geometry, Quantum Mechanics and Applications</strong> -- Agriturismo Erbanito, San Rufo (Salerno), Italy, July 2018. Organizing committee. [<a href="https://agenda.infn.it/event/15444/">conference</a>] [<a href="https://web.archive.org/web/20240302140910/https://agenda.infn.it/event/15444/">conference-archive</a>]</li>

<li><strong>Current Problems in Theoretical Physics XXIV</strong> -- Lloyd's Baia Hotel, Vietri sul Mare, Italy, March 2018. Local organizer. [<a href="http://paft18.sa.infn.it/index.html">conference</a>]</li>

<li><strong>Information Geometry, Quantum Mechanics and Applications</strong> -- Agriturismo Erbanito, San Rufo (Salerno), Italy, July 2017. Organizing committee. [<a href="https://agenda.infn.it/event/13817/attachments/15086/17043/QUINFOGEO_POSTER.pdf">conference</a>] [<a href="https://web.archive.org/web/20240216140528/https://agenda.infn.it/event/13817/attachments/15086/17043/QUINFOGEO_POSTER.pdf">conference-archive</a>]</li>
</ol>

## Presentations and talks:
<ol reversed>
<li><strong>Look: it's GNS Hilbert spaces everywhere!</strong> -- Geometry and Dynamics, Naples, Italy, January 2026. [<a href="https://agenda.infn.it/event/48741/">conference</a>] [<a href="https://web.archive.org/web/20260120161850/https://agenda.infn.it/event/48741/">conference-archive</a>] [<a href="https://agenda.infn.it/event/48741/page/10955-program-in-short">program</a>] [<a href="https://web.archive.org/web/20260120163351/https://agenda.infn.it/event/48741/page/10955-program-in-short">program-archive</a>] [<a href="/presentations/2026-01-14-GNS-everywhere/index.qmd">presentation</a>]</li>

<li><strong>The geometry of classical and quantum states</strong> -- XXXIX RSEF Physics Biennial, Donostia/San Sebastián, Spain, July 2024. [<a href="https://bienalfisica.org/en/symposia#headingSimposio15">conference</a>] [<a href="https://web.archive.org/web/20241006210554/https://bienalfisica.org/en/symposia#headingSimposio15">conference-archive</a>] </li>

<li><strong>Can Čencov meet Petz?</strong> -- V International Workshop of Information Geometry, Quantum Mechanics and Applications 2023, UC3M, Madrid, Spain, March 2023. [<a href="http://q-math.es/conferences/IGQMA2023/Timetable.php">timetable</a>] [<a href="https://web.archive.org/web/20230530053524/http://q-math.es/conferences/IGQMA2023/Timetable.php">timetable-archive</a>]</li>

<li><strong>Can Čencov meet Petz?</strong> -- Q-Math Seminars, UC3M, Madrid, Spain, January 2023. [<a href="http://www.q-math.es/Other.php?year=2022/2023">seminar</a>] [<a href="https://web.archive.org/web/20240302134048/http://www.q-math.es/Other.php?year=2022/2023">seminar-archive</a>]</li>

<li><strong>Jordan algebras, coadjoint orbits, and information geometry</strong> -- Prague-Hradec Králové seminar on Cohomology in algebra, geometry, physics and statistics, December 2022. [<a href="https://www.youtube.com/watch?v=XwLNWW193xQ">video</a>]</li>

<li><strong>The Information Geometry of Jordan algebras</strong> -- Virtual Meeting on Information Geometry 2021, Università di Bologna, May 2021. [<a href="https://eventi.unibo.it/infogeo2021/program">conference</a>] [<a href="https://www.youtube.com/watch?v=1u1-TFP9yBY">video</a>]</li>

<li><strong>A groupoid-based perspective on Quantum Mechanics</strong> -- Topological Quantum Field Theory Seminar, Técnico Lisboa, January 2021. [<a href="https://tqft.math.tecnico.ulisboa.pt/seminars">seminar</a>]</li>

<li><strong>Gently wandering through the space of quantum states, relating metric tensors with group actions</strong> -- Max Planck Institute for Mathematics in the Sciences, Leipzig, Germany, April 2020. [<a href="https://www.mis.mpg.de/events/event/gently-wandering-through-the-space-of-quantum-states-relating-metric-tensors-with-group-actions">seminar</a>] [<a href="https://web.archive.org/web/20260120164434/https://www.mis.mpg.de/events/event/gently-wandering-through-the-space-of-quantum-states-relating-metric-tensors-with-group-actions">seminar-archive</a>]</li>

<li><strong>On the notion of composite systems</strong> -- Geometric Science of Information GSI'19, Toulouse, France, August 2019. [<a href="https://web2.see.asso.fr/en/fichier/26060_schedule-and-final-program">timetable</a>]</li>

<li><strong>The Jordan product, the Fisher-Rao metric tensor, and the Bures-Uhlmann metric tensor</strong> -- Information Geometry, Quantum Mechanics and Applications III, Grajera (Segovia), Spain, June 2019. [<a href="http://q-math.es/conferences/IGQMA2019/Timetable.php">timetable</a>]</li>

<li><strong>A gentle introduction to Schwinger's picture and groupoids in Quantum Mechanics</strong> -- Information Geometry, Quantum Mechanics and Applications II, San Rufo (Salerno), Italy, July 2018. [<a href="https://agenda.infn.it/event/15444/">conference</a>] [<a href="https://web.archive.org/web/20240302140910/https%3A%2F%2Fagenda.infn.it%2Fevent%2F15444%2F">conference-archive</a>] [<a href="https://agenda.infn.it/event/15444/timetable/#20180627">timetable</a>] [<a href="https://web.archive.org/web/20241006211846/https://agenda.infn.it/event/15444/timetable/#20180627">timetable-archive</a>]</li>

<li><strong>The space of quantum states relative entropies and metric tensors</strong> -- Current Problems in Theoretical Physics XXIV, Vietri sul Mare, Italy, March 2018. [<a href="http://paft18.sa.infn.it/index.html">conference</a>]</li>

<li><strong>The space of quantum states, relative entropies and metric tensors</strong> -- 60 Years Alberto Ibort Fest - Classical and Quantum Physics: Geometry, Dynamics and Control, Madrid, Spain, March 2018. [<a href="https://www.icmat.es/congresos/2018/IBORT-FEST/speakers.php">conference</a>]</li>

<li><strong>The space of quantum states, relative entropies and metric tensors</strong> -- Max Planck Institute for Mathematics in Science, Leipzig, Germany, January 2018. [<a href="https://www.mis.mpg.de/events/event/the-space-of-quantum-states-relative-entropies-and-metric-tensors">seminar</a>] [<a href="https://web.archive.org/web/20260120165112/https://www.mis.mpg.de/events/event/the-space-of-quantum-states-relative-entropies-and-metric-tensors">seminar-archive</a>]</li>

<li><strong>Hamilton-Jacobi theory and Information Geometry</strong> — Geometric Science of Information GSI'17, Paris, France, October 2017. [<a href="https://web2.see.asso.fr/wiki/19413_program">timetable</a>]</li>

<li><strong>Metric tensors on the space of invertible quantum states</strong> -- XXVI International fall workshop on Geometry and Physics, Braga, Portugal, August 2017. [<a href="https://w3.math.uminho.pt/~agarciaparrado/IFWGP/index.html">conference</a>] [<a href="https://web.archive.org/web/20260120165637/https://w3.math.uminho.pt/~agarciaparrado/IFWGP/index.html">conference-archive</a>] [<a href="https://w3.math.uminho.pt/~agarciaparrado/IFWGP/Program.html">timetable</a>] [<a href="https://web.archive.org/web/20260120165719/https://w3.math.uminho.pt/~agarciaparrado/IFWGP/Program.html">timetable-archive</a>] [<a href="https://w3.math.uminho.pt/~agarciaparrado/IFWGP/Participants.php">speakers</a>] [<a href="https://web.archive.org/web/20260120165838/https://w3.math.uminho.pt/~agarciaparrado/IFWGP/Participants.php">speakers-archive</a>]</li>

<li><strong>A differential geometric approach to the geometry of quantum states</strong> -- Information Geometry, Quantum Mechanics and Applications, San Rufo (Salerno), Italy, June 2017. [<a href="https://agenda.infn.it/event/13817/attachments/15086/17043/QUINFOGEO_POSTER.pdf">conference</a>] [<a href="https://web.archive.org/web/20240216140528/https://agenda.infn.it/event/13817/attachments/15086/17043/QUINFOGEO_POSTER.pdf">conference-archive</a>]</li>

<li><strong>Time, classical and quantum</strong> -- XXV International fall workshop on Geometry and Physics, Madrid, Spain, 2016. [<a href="https://www.icmat.es/congresos/2016/XXVIFWGP/schedule.php">conference</a>]</li>

<li><strong>Time, classical and quantum</strong> -- INFN Quantum Meeting, Trieste, Italy, 2016.</li>

<li><strong>Time, classical and quantum</strong> -- I.Q.I.S. 2015, Monopoli, Italy, 2015.</li>
</ol>


