---
title: "Home"
format: html
comments: false
---

I was born and raised in <a href="https://sscnapoli.it/en" target="_blank" rel="noopener">Napoli</a> where I grew up eating pizza, reading books and manga, playing guitar, and, most importantly, wondering about abstractness during my BSc, MSc, and PhD at the <a href="http://www.unina.it/en_GB/home" target="_blank" rel="noopener">Università degli Studi di Napoli Federico II</a> under the supervision of G. Marmo.

## Academic trajectory

- <a href="https://web.archive.org/web/20220629195404/https://researchportal.uc3m.es/display/inv48159" target="_blank" rel="noopener">July 2021</a> - <a href="https://web.archive.org/web/20230227140911/https://researchportal.uc3m.es/display/inv48159" target="_blank" rel="noopener">Present</a>: <em>Investigador distinguido</em> in the Department of Mathematics at the Universidad Carlos III de Madrid (UC3M), in the <a href="http://www.q-math.es/group/">Q-Math research group</a>.
- <a href="https://web.archive.org/web/20230227142855/https://www.mis.mpg.de/jjost/members/florio-maria-ciaglia.html" target="_blank" rel="noopener">July 2018</a> - <a href="https://web.archive.org/web/20230227115316/https://www.mis.mpg.de/jjost/former-group-members.html" target="_blank" rel="noopener">June 2021</a>: <em>Postdoctoral researcher</em> in J. Jost's group at the Max Planck Institute for the Mathematics in the Sciences (MIS-MPG).</li>

## Research projects and evaluations

- November 2025 - Acreditación a Profesor/a Titular de Universidad en Matemáticas (ANECA).
- <a href="https://web.archive.org/web/20251121095849/https://researchportal.uc3m.es/display/act577570" target="_blank" rel="noopener">September 2025</a> - Principal researcher of the project "CGAIFT - Categories, groupoids and their algebras in information and theories of fields", 09/2025 - 08/2028.
- <a href="https://web.archive.org/web/20251121095601/https://researchportal.uc3m.es/display/act570949" target="_blank" rel="noopener">January 2025</a> - Principal researcher of the project "QUITEMAD", 01/2025 - 12/2028.
- <a href="https://www.cost.eu/actions/CA21109/#tabs+Name:Management%20Committee" target="_blank" rel="noopener">January 2025</a> - Spain national representative in the management committee of the COST project "CaLISTA", 10/2022 - 10/2026.
- June 2023, Sexenio de investigación en Matemáticas y Física, tramo 2015/2021.
- <a href="https://web.archive.org/web/20230227113547/https://researchportal.uc3m.es/display/act547251" target="_blank" rel="noopener">November 2021</a> - Principal researcher of the project "Classical and Quantum Information Theory and Functional Analysis: Foundations and applications, 11/2021 - 12/2024.
- <a href="https://web.archive.org/web/20230227113103/https://researchportal.uc3m.es/display/act537810" target="_blank" rel="noopener">September 2021</a> - Member of the research team of the project "GRUPOIDES, ALGEBRAS DE VON NEUMANN Y LOS FUNDAMENTOS MATEMATICOS DE LA MECANICA CUANTICA: TEORIA Y APLICACIONES, 09/2021 - 08/2025.
- <a href="https://web.archive.org/web/20230227142414/https://asn18.cineca.it/pubblico/miur/esito-abilitato/02%252FA2/2/6" target="_blank" rel="noopener">April 2021</a> - Abilitazione Scientifica Nazionale (ASN) in Fisica teorica e Fisica delle Interazioni Fondamentali, settore concorsuale 02/A2. 
- <a href="https://web.archive.org/web/20210506134618/https://www.educacionyfp.gob.es/servicios-al-ciudadano/catalogo/general/27/277089/ficha/277089-2019.html" target="_blank" rel="noopener">September 2020</a> - Ayuda <em>Beatriz Galindo</em> for a (4+1)-year position at the UC3M.

## Editorial work

- <a href="https://web.archive.org/web/20210614160350/https://epjplus.epj.org/epjplus-editorial-board" target="_blank" rel="noopener">February 2021</a> - <a href="https://web.archive.org/web/20230227142730/https://epjplus.epj.org/epjplus-editorial-board" target="_blank" rel="noopener">Present</a>: Editor for the <em>European Physical Journal Plus</em>.
- November 2020 - Present: <a href="https://loop.frontiersin.org/people/987848/overview" target="_blank" rel="noopener">Review Editor</a> for <em>Frontiers in Physics</em> and <em>Frontiers in Applied Mathematics and Statistics</em>.
 
## Digital places where I appear

- <a href="https://dcrowley.academia.edu/FlorioMCiaglia" target="_blank" rel="noopener">Academia</a>         
- <a href="https://arxiv.org/a/ciaglia_f_1.html" target="_blank" rel="noopener">arXiv </a>         
- <a href="https://scholar.google.com/citations?user=gr5N5wUAAAAJ&amp;hl=en&amp;oi=ao" target="_blank" rel="noopener">Google Scholar</a>          
- <a href="https://inspirehep.net/author/profile/F.M.Ciaglia.1" target="_blank" rel="noopener">INSPIRE</a>          
- <a href="https://www.linkedin.com/in/florio-m-ciaglia-18ab5b136/" target="_blank" rel="noopener">LinkedIn</a>
- <a href="https://loop.frontiersin.org/people/987848/overview" target="_blank" rel="noopener">Loop</a>          
- <a href="https://mathscinet.ams.org/mathscinet/MRAuthorID/1181735" target="_blank" rel="noopener">MathSciNet</a>         
- <a href="https://orcid.org/0000-0002-8987-1181" target="_blank" rel="noopener">ORCID</a>                 
- <a href="https://www.researchgate.net/profile/Florio_Maria_Ciaglia" target="_blank" rel="noopener">ResearchGate</a>
- <a href="https://sciprofiles.com/profile/786705" target="_blank" rel="noopener">SciProfiles</a>          
- <a href="https://scirate.com/fmc2" target="_blank" rel="noopener">SciRate</a>          
- <a href="https://www.scopus.com/authid/detail.uri?authorId=57190577826" target="_blank" rel="noopener">Scopus</a>          
- <a href="https://www.semanticscholar.org/author/Florio-M.-Ciaglia/27675900" target="_blank" rel="noopener">Semantic Scholar</a>
- <a href="https://www.webofscience.com/wos/author/record/374444" target="_blank" rel="noopener">Web of Science</a>  
- <a href="https://www.wikidata.org/wiki/Q103832189" target="_blank" rel="noopener">Wikidata</a>   

## Music

I like music and I used to play guitar.

I recorded the EP <a href="https://soundcloud.com/artrepaz" target="_blank" rel="noopener"><em>Via Soffritto</em></a>  neapolitan rock-blues band <a href="https://www.youtube.com/user/artrepaz" target="_blank" rel="noopener">ArtRePaz</a>. I was the lead guitar and we had a lot of fun before the bitterness of life chewed to death our rock 'n roll dreams.

I also have a <a href="https://ilcap1tan0.bandcamp.com/releases" target="_blank" rel="noopener">Bandcamp page</a> I seldomly update. There is no logic, nor beauty, nor any kind of sense in it, but I like it nonetheless.